SRCS       := src/dhrystone_main.c src/dhrystone.c src/util.c
APP        := dhrystone
CCFLAGS    := -O3 -fno-inline -march=rv32imac_zicsr_zifencei -Wno-implicit-function-declaration -Wno-implicit-int

INCDIR := .

include ../common/common.mk
